min_particles : 10
max_particles : 200
transform_tolerance: 1
initial_pose_x : 0.0
initial_pose_y : 0.0
initial_pose_a : 1.5


laser_min_range : -1
laser_max_range : -1
laser_model_type : likelihood_field
laser_likelihood_max_dist : 1


odom_model_type : diff-corrected 
odom_alpha1 : 0.008 
odom_alpha2 : 0.008
odom_alpha3 : 0.008
odom_alpha4 : 0.008

odom_frame_id : odom
base_frame_id : robot_footprint
global_frame_id : map